name: glfw3
description: A Dart library for accessing common glfw 3.3.9 APIs using, FFI.
version: 1.2.1
homepage: https://github.com/sansuido/glfw3
repository: https://github.com/sansuido/glfw3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  ffi: ^2.1.2

dev_dependencies:
  lints: ^3.0.0

